# Generated by Django 5.0.7 on 2024-07-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_tarefa_delete_listatarefas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateField(blank=True, default='None'),
        ),
    ]
