# Generated by Django 5.0.7 on 2024-07-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_tarefa_data_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
